### ISSUE TITLE
Divide by zero exception when using Basic Algorithm

### ISSUE THREAD

**Issue by captainjackrana** [xdrop/fuzzywuzzy#31]
Upon using a string that has only non-alphanumeric characters (Eg: "$#"), The Basic Algorithm throws the following exception
`java.lang.ArithmeticException: / by zero
	at me.xdrop.fuzzywuzzy.algorithms.WeightedRatio.apply(WeightedRatio.java:32)
	at me.xdrop.fuzzywuzzy.algorithms.BasicAlgorithm.apply(BasicAlgorithm.java:22)
	at me.xdrop.fuzzywuzzy.Extractor.extractWithoutOrder(Extractor.java:43)
	at me.xdrop.fuzzywuzzy.Extractor.extractTop(Extractor.java:100)
`

I believe this is resulting due to the String processor replacing the characters by spaces and then trimming it which results in the string length to become zero

**Comment by xdrop** [comment]
Yes it is, I think in such a case the ratio returned should be zero. I will add a fix for this in the next patch
