### ISSUE TITLE
StringIndexOutOfBoundsException in partialratio

### ISSUE THREAD

**Issue by kartheekgurram** [xdrop/fuzzywuzzy#9]
java.lang.StringIndexOutOfBoundsException: String index out of range: 49
        at java.lang.String.substring(String.java:1963)
        at com.xdrop.fuzzywuzzy.ratios.PartialRatio.apply(PartialRatio.java:43)
        at com.xdrop.fuzzywuzzy.FuzzySearch.partialRatio(FuzzySearch.java:45)

test case:
FuzzySearch.partialRatio("pros holdings, inc.","settlement facility dow corning trust")

**Comment by kartheekgurram** [comment]
I could fix it by doing this : 
String long_substr = longer.substring(long_start,long_end>longer.length()?longer.length():long_end);

**Comment by xdrop** [comment]
Thanks for reporting this!

Should be fixed by #10
